package net.jrodolfo.llm.rag.dto;

import net.jrodolfo.llm.dto.ModelProviderMetadata;
import net.jrodolfo.llm.dto.RagRetrievalMetadata;
import net.jrodolfo.llm.dto.RagTimingMetadata;

import java.util.List;

/**
 * Response DTO containing the answer generated by the RAG system and its supporting sources.
 *
 * @param answer    The generated answer string.
 * @param provider  The LLM provider used to generate the answer.
 * @param model     The specific model used to generate the answer.
 * @param sessionId The unique identifier for the current session.
 * @param sources   The list of source chunks used to augment the prompt.
 * @param metadata  Additional metadata from the model provider.
 * @param ragRetrieval Retrieval target metadata for the RAG request.
 * @param ragTiming Backend timing metadata for the RAG request.
 */
public record RagQueryResponse(
        String answer,
        String provider,
        String model,
        String sessionId,
        List<RagSourceChunkResponse> sources,
        ModelProviderMetadata metadata,
        RagRetrievalMetadata ragRetrieval,
        RagTimingMetadata ragTiming
) {
}
