package net.jrodolfo.llm.client;

import net.jrodolfo.llm.dto.ModelProviderMetadata;
import net.jrodolfo.llm.provider.ProviderPromptMessage;
import software.amazon.awssdk.services.bedrockruntime.BedrockRuntimeAsyncClient;
import software.amazon.awssdk.services.bedrockruntime.BedrockRuntimeClient;
import software.amazon.awssdk.services.bedrockruntime.model.*;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Consumer;
import java.util.stream.Collectors;

/**
 * Bedrock runtime adapter backed by the AWS SDK v2 converse APIs.
 *
 * <p>The gateway keeps Bedrock-specific event handling out of the provider layer and converts both
 * normal and streaming responses into the project's provider metadata model.
 *
 * <p>Implementation of {@link BedrockRuntimeGateway} using the AWS SDK for Java v2.
 * This gateway provides methods to interact with the Amazon Bedrock Runtime service,
 * supporting both synchronous and streaming model invocations.
 */
public class AwsSdkBedrockRuntimeGateway implements BedrockRuntimeGateway {

    private final BedrockRuntimeClient bedrockRuntimeClient;
    private final BedrockRuntimeAsyncClient bedrockRuntimeAsyncClient;

    /**
     * Constructs a new {@code AwsSdkBedrockRuntimeGateway} with the specified clients.
     *
     * @param bedrockRuntimeClient      the synchronous Bedrock runtime client
     * @param bedrockRuntimeAsyncClient the asynchronous Bedrock runtime client
     */
    public AwsSdkBedrockRuntimeGateway(
            BedrockRuntimeClient bedrockRuntimeClient,
            BedrockRuntimeAsyncClient bedrockRuntimeAsyncClient
    ) {
        this.bedrockRuntimeClient = bedrockRuntimeClient;
        this.bedrockRuntimeAsyncClient = bedrockRuntimeAsyncClient;
    }

    /**
     * Performs a single-turn synchronous conversation with the specified model using a simple text prompt.
     *
     * @param prompt  the text prompt to send to the model
     * @param modelId the ID of the model to use
     * @return a {@link ModelProviderReply} containing the model's response and metadata
     * @throws ModelProviderException if the conversation fails
     */
    @Override
    public ModelProviderReply converse(String prompt, String modelId) {
        try {
            long startedAt = System.currentTimeMillis();
            ConverseRequest request = buildConverseRequest(buildUserMessage(prompt), List.of(), modelId);
            ConverseResponse response = bedrockRuntimeClient.converse(request);
            return toReply(response, modelId, startedAt);
        } catch (RuntimeException ex) {
            throw new ModelProviderException(classifyBedrockFailure(ex, false), ex);
        }
    }

    /**
     * Performs a synchronous conversation with the specified model using a list of structured messages.
     *
     * @param messages a list of {@link ProviderPromptMessage} objects representing the conversation history
     * @param modelId  the ID of the model to use
     * @return a {@link ModelProviderReply} containing the model's response and metadata
     * @throws ModelProviderException if the conversation fails
     */
    @Override
    public ModelProviderReply converse(List<ProviderPromptMessage> messages, String modelId) {
        try {
            long startedAt = System.currentTimeMillis();
            StructuredBedrockPrompt prompt = toStructuredPrompt(messages);
            ConverseRequest request = buildConverseRequest(prompt.messages(), prompt.system(), modelId);
            ConverseResponse response = bedrockRuntimeClient.converse(request);
            return toReply(response, modelId, startedAt);
        } catch (RuntimeException ex) {
            throw new ModelProviderException(classifyBedrockFailure(ex, false), ex);
        }
    }

    /**
     * Performs a single-turn streaming conversation with the specified model using a simple text prompt.
     *
     * @param prompt        the text prompt to send to the model
     * @param modelId       the ID of the model to use
     * @param chunkConsumer a consumer that receives text chunks as they are generated by the model
     * @return a {@link CompletableFuture} that completes with the final {@link ModelProviderMetadata}
     * @throws ModelProviderException if the streaming process fails to initiate
     */
    @Override
    public CompletableFuture<ModelProviderMetadata> converseStream(String prompt, String modelId, Consumer<String> chunkConsumer) {
        try {
            ConverseStreamRequest request = buildConverseStreamRequest(buildUserMessage(prompt), List.of(), modelId);
            return stream(request, modelId, chunkConsumer);
        } catch (RuntimeException ex) {
            throw new ModelProviderException(classifyBedrockFailure(ex, true), ex);
        }
    }

    /**
     * Performs a streaming conversation with the specified model using a list of structured messages.
     *
     * @param messages      a list of {@link ProviderPromptMessage} objects representing the conversation history
     * @param modelId       the ID of the model to use
     * @param chunkConsumer a consumer that receives text chunks as they are generated by the model
     * @return a {@link CompletableFuture} that completes with the final {@link ModelProviderMetadata}
     * @throws ModelProviderException if the streaming process fails to initiate
     */
    @Override
    public CompletableFuture<ModelProviderMetadata> converseStream(
            List<ProviderPromptMessage> messages,
            String modelId,
            Consumer<String> chunkConsumer
    ) {
        try {
            StructuredBedrockPrompt prompt = toStructuredPrompt(messages);
            ConverseStreamRequest request = buildConverseStreamRequest(prompt.messages(), prompt.system(), modelId);
            return stream(request, modelId, chunkConsumer);
        } catch (RuntimeException ex) {
            throw new ModelProviderException(classifyBedrockFailure(ex, true), ex);
        }
    }

    /**
     * Internal helper to handle the streaming logic using the AWS SDK v2 async client.
     *
     * @param request       the {@link ConverseStreamRequest} to send
     * @param modelId       the model ID being used
     * @param chunkConsumer a consumer for text chunks
     * @return a future providing the final metadata once the stream completes
     */
    private CompletableFuture<ModelProviderMetadata> stream(
            ConverseStreamRequest request,
            String modelId,
            Consumer<String> chunkConsumer
    ) {
        long startedAt = System.currentTimeMillis();
        AtomicReference<String> stopReason = new AtomicReference<>();
        AtomicReference<TokenUsage> usage = new AtomicReference<>();
        AtomicReference<ConverseStreamMetrics> metrics = new AtomicReference<>();
        CompletableFuture<ModelProviderMetadata> metadataFuture = new CompletableFuture<>();

        ConverseStreamResponseHandler handler = ConverseStreamResponseHandler.builder()
                .subscriber(ConverseStreamResponseHandler.Visitor.builder()
                        .onContentBlockDelta(event -> forwardChunk(event, chunkConsumer))
                        .onMessageStop(event -> captureStopReason(event, stopReason))
                        .onMetadata(event -> captureMetadata(event, usage, metrics))
                        .build())
                .onError(error -> metadataFuture.completeExceptionally(
                        new ModelProviderException(classifyBedrockFailure(error, true), error)
                ))
                .onComplete(() -> {
                    TokenUsage finalUsage = usage.get();
                    ConverseStreamMetrics finalMetrics = metrics.get();
                    metadataFuture.complete(new ModelProviderMetadata(
                            "bedrock",
                            modelId,
                            stopReason.get(),
                            finalUsage != null ? finalUsage.inputTokens() : null,
                            finalUsage != null ? finalUsage.outputTokens() : null,
                            finalUsage != null ? finalUsage.totalTokens() : null,
                            System.currentTimeMillis() - startedAt,
                            finalMetrics != null ? finalMetrics.latencyMs() : null,
                            null,
                            null
                    ));
                })
                .build();

        CompletableFuture<Void> streamFuture = bedrockRuntimeAsyncClient.converseStream(request, handler);
        // Cancellation is driven by the controller when the SSE client disconnects.
        metadataFuture.whenComplete((ignored, throwable) -> {
            if (metadataFuture.isCancelled()) {
                streamFuture.cancel(true);
            }
        });
        streamFuture.whenComplete((ignored, throwable) -> {
            if (throwable != null) {
                metadataFuture.completeExceptionally(new ModelProviderException(
                        classifyBedrockFailure(unwrapCompletionException(throwable), true),
                        unwrapCompletionException(throwable)
                ));
            }
        });
        return metadataFuture;
    }

    /**
     * Builds a synchronous {@link ConverseRequest}.
     *
     * @param messages the list of conversation messages
     * @param system   the list of system blocks
     * @param modelId  the model ID
     * @return a configured {@code ConverseRequest}
     */
    private ConverseRequest buildConverseRequest(List<Message> messages, List<SystemContentBlock> system, String modelId) {
        return ConverseRequest.builder()
                .modelId(modelId)
                .messages(messages)
                .system(system)
                .build();
    }

    /**
     * Builds a {@link ConverseStreamRequest}.
     *
     * @param messages the list of conversation messages
     * @param system   the list of system blocks
     * @param modelId  the model ID
     * @return a configured {@code ConverseStreamRequest}
     */
    private ConverseStreamRequest buildConverseStreamRequest(List<Message> messages, List<SystemContentBlock> system, String modelId) {
        return ConverseStreamRequest.builder()
                .modelId(modelId)
                .messages(messages)
                .system(system)
                .build();
    }

    /**
     * Wraps a simple text prompt into a single user message.
     *
     * @param prompt the text prompt
     * @return a list containing one user message
     */
    private List<Message> buildUserMessage(String prompt) {
        return List.of(Message.builder()
                .role(ConversationRole.USER)
                .content(ContentBlock.fromText(prompt))
                .build());
    }

    /**
     * Converts project-agnostic {@link ProviderPromptMessage}s into Bedrock-specific messages and system blocks.
     *
     * @param providerMessages the list of incoming messages
     * @return a {@link StructuredBedrockPrompt} containing sorted messages and system blocks
     * @throws ModelProviderException if a role is unsupported or no user/assistant messages are found
     */
    private StructuredBedrockPrompt toStructuredPrompt(List<ProviderPromptMessage> providerMessages) {
        List<Message> messages = new ArrayList<>();
        List<SystemContentBlock> system = new ArrayList<>();

        for (ProviderPromptMessage providerMessage : providerMessages) {
            if (providerMessage == null || providerMessage.content() == null || providerMessage.content().isBlank()) {
                continue;
            }

            String role = providerMessage.role() == null ? "" : providerMessage.role().trim().toLowerCase();
            switch (role) {
                case "system" -> system.add(SystemContentBlock.fromText(providerMessage.content()));
                case "user" -> messages.add(toBedrockMessage(ConversationRole.USER, providerMessage.content()));
                case "assistant" ->
                        messages.add(toBedrockMessage(ConversationRole.ASSISTANT, providerMessage.content()));
                default ->
                        throw new ModelProviderException("Unsupported Bedrock prompt role: " + providerMessage.role());
            }
        }

        if (messages.isEmpty()) {
            throw new ModelProviderException("Bedrock structured prompt must contain at least one user or assistant message.");
        }

        return new StructuredBedrockPrompt(List.copyOf(messages), List.copyOf(system));
    }

    /**
     * Helper to create a Bedrock {@link Message} for a given role and content.
     *
     * @param role    the Bedrock {@link ConversationRole}
     * @param content the text content
     * @return a {@link Message} instance
     */
    private Message toBedrockMessage(ConversationRole role, String content) {
        return Message.builder()
                .role(role)
                .content(ContentBlock.fromText(content))
                .build();
    }

    /**
     * Converts a {@link ConverseResponse} into the internal {@link ModelProviderReply} model.
     *
     * @param response  the response from Bedrock
     * @param modelId   the model ID used
     * @param startedAt the timestamp when the request started
     * @return a {@link ModelProviderReply}
     * @throws ModelProviderException if the response is empty or malformed
     */
    private ModelProviderReply toReply(ConverseResponse response, String modelId, long startedAt) {
        if (response.output() == null || response.output().message() == null || response.output().message().content() == null) {
            throw new ModelProviderException("Bedrock response did not contain message content.");
        }
        String output = response.output().message().content().stream()
                .map(ContentBlock::text)
                .filter(text -> text != null && !text.isBlank())
                .collect(Collectors.joining());
        if (output.isBlank()) {
            throw new ModelProviderException("Bedrock response did not contain text output.");
        }
        ModelProviderMetadata metadata = new ModelProviderMetadata(
                "bedrock",
                modelId,
                response.stopReason() != null ? response.stopReasonAsString() : null,
                response.usage() != null ? response.usage().inputTokens() : null,
                response.usage() != null ? response.usage().outputTokens() : null,
                response.usage() != null ? response.usage().totalTokens() : null,
                System.currentTimeMillis() - startedAt,
                response.metrics() != null ? response.metrics().latencyMs() : null,
                null,
                null
        );
        return new ModelProviderReply(output, metadata);
    }

    /**
     * Simple record to hold the separated messages and system blocks for Bedrock.
     */
    private record StructuredBedrockPrompt(
            List<Message> messages,
            List<SystemContentBlock> system
    ) {
    }

    /**
     * Extracts and forwards text chunks from a stream event to the consumer.
     *
     * @param event         the content block delta event
     * @param chunkConsumer the consumer of the text
     */
    private void forwardChunk(ContentBlockDeltaEvent event, Consumer<String> chunkConsumer) {
        if (event.delta() == null || event.delta().text() == null || event.delta().text().isBlank()) {
            return;
        }
        chunkConsumer.accept(event.delta().text());
    }

    /**
     * Captures the stop reason from a stream event.
     *
     * @param event      the message stop event
     * @param stopReason the atomic reference to store the stop reason
     */
    private void captureStopReason(MessageStopEvent event, AtomicReference<String> stopReason) {
        if (event.stopReason() != null) {
            stopReason.set(event.stopReasonAsString());
        }
    }

    /**
     * Captures usage and performance metrics from a stream event.
     *
     * @param event   the metadata event
     * @param usage   the atomic reference for token usage
     * @param metrics the atomic reference for metrics
     */
    private void captureMetadata(
            ConverseStreamMetadataEvent event,
            AtomicReference<TokenUsage> usage,
            AtomicReference<ConverseStreamMetrics> metrics
    ) {
        if (event.usage() != null) {
            usage.set(event.usage());
        }
        if (event.metrics() != null) {
            metrics.set(event.metrics());
        }
    }

    /**
     * Unwraps {@link CompletionException} to get the underlying cause.
     *
     * @param throwable the throwable to unwrap
     * @return the cause if it's a {@code CompletionException}, otherwise the original throwable
     */
    private Throwable unwrapCompletionException(Throwable throwable) {
        if (throwable instanceof CompletionException completionException && completionException.getCause() != null) {
            return completionException.getCause();
        }
        return throwable;
    }

    /**
     * Classifies Bedrock SDK exceptions into user-friendly error messages.
     *
     * @param throwable the exception to classify
     * @param streaming whether the exception occurred during a streaming operation
     * @return a descriptive error message
     */
    private String classifyBedrockFailure(Throwable throwable, boolean streaming) {
        String operation = streaming ? "stream" : "request";
        if (throwable instanceof ValidationException ex) {
            return "Bedrock request validation failed: " + ex.getMessage();
        }
        String message = throwable.getMessage();
        String lowerMessage = message == null ? "" : message.toLowerCase();
        if (lowerMessage.contains("security token")
                || lowerMessage.contains("access denied")
                || lowerMessage.contains("unable to load credentials")
                || lowerMessage.contains("not authorized")) {
            return "Bedrock authentication failed. Check AWS credentials, profile, and model access.";
        }
        if (lowerMessage.contains("resource not found")
                || lowerMessage.contains("model not found")
                || lowerMessage.contains("inference profile")
                || lowerMessage.contains("not supported on-demand throughput")) {
            return "The selected Bedrock model or inference profile is unavailable in the configured region.";
        }
        if (lowerMessage.contains("timed out") || lowerMessage.contains("timeout")) {
            return "Bedrock " + operation + " timed out. Try again or use a different model.";
        }
        if (lowerMessage.contains("connection refused")
                || lowerMessage.contains("unknown host")
                || lowerMessage.contains("failed to connect")) {
            return "Bedrock endpoint is unreachable. Check network access and AWS region configuration.";
        }
        return streaming
                ? "Failed to stream from Bedrock."
                : "Failed to call Bedrock converse endpoint.";
    }
}
