package net.jrodolfo.llm.client;

import net.jrodolfo.llm.provider.ProviderPromptMessage;

import java.util.List;
import java.util.function.Consumer;
import java.util.concurrent.CompletableFuture;

/**
 * Gateway interface for interacting with the Amazon Bedrock Runtime.
 * Provides methods for synchronous and asynchronous (streaming) model invocations.
 */
public interface BedrockRuntimeGateway {

    /**
     * Performs a single-turn synchronous conversation with the specified model using a simple text prompt.
     *
     * @param prompt  the text prompt to send to the model
     * @param modelId the ID of the model to use
     * @return a {@link ModelProviderReply} containing the model's response and metadata
     */
    ModelProviderReply converse(String prompt, String modelId);

    /**
     * Performs a synchronous conversation with the specified model using a list of structured messages.
     *
     * @param messages a list of {@link ProviderPromptMessage} objects representing the conversation history
     * @param modelId  the ID of the model to use
     * @return a {@link ModelProviderReply} containing the model's response and metadata
     */
    ModelProviderReply converse(List<ProviderPromptMessage> messages, String modelId);

    /**
     * Performs a single-turn streaming conversation with the specified model using a simple text prompt.
     *
     * @param prompt        the text prompt to send to the model
     * @param modelId       the ID of the model to use
     * @param chunkConsumer a consumer that receives text chunks as they are generated by the model
     * @return a {@link CompletableFuture} that completes with the final {@link net.jrodolfo.llm.dto.ModelProviderMetadata}
     */
    CompletableFuture<net.jrodolfo.llm.dto.ModelProviderMetadata> converseStream(String prompt, String modelId, Consumer<String> chunkConsumer);

    /**
     * Performs a streaming conversation with the specified model using a list of structured messages.
     *
     * @param messages      a list of {@link ProviderPromptMessage} objects representing the conversation history
     * @param modelId       the ID of the model to use
     * @param chunkConsumer a consumer that receives text chunks as they are generated by the model
     * @return a {@link CompletableFuture} that completes with the final {@link net.jrodolfo.llm.dto.ModelProviderMetadata}
     */
    CompletableFuture<net.jrodolfo.llm.dto.ModelProviderMetadata> converseStream(
            List<ProviderPromptMessage> messages,
            String modelId,
            Consumer<String> chunkConsumer
    );
}
