package net.jrodolfo.llm.client;

import net.jrodolfo.llm.dto.ModelProviderMetadata;

/**
 * Represents a reply from a model provider.
 *
 * @param text     The text generated by the model.
 * @param metadata Metadata associated with the model's response.
 */
public record ModelProviderReply(
        String text,
        ModelProviderMetadata metadata
) {
}
